# Copyright (c) Meta Platforms, Inc. and affiliates.
# All rights reserved.

# This source code is licensed under the license found in the
# LICENSE file in the root directory of this source tree.

type: 'scene'

PerspectiveCamera:
  type: 'perspective'
  fov: 45
  film:
    type: 'hdrfilm'
    width: 1920
    height: 1080
    rfilter:
      type: 'box'
  
Integrator:
  type: 'path'
  max_depth: 7

main_scene:
  type: 'ply'
  filename: ''
  bsdf:
    type: 'twosided'
    fipt_bsdf:
      type: 'fipt'
      emitter_path: ''
      brdf_path: ''

emitter_bathroom2:
  type: 'ply'
  filename: 'checkpoints/scannetpp_bathroom2/bake/emitter.ply'
  to_world:
    - type: 'translate'
      value: [0.0, 0.0, 0.0]
    - type: 'scale'
      value: [1.0, 1.0, 1.0]
  bsdf:
    type: 'diffuse'
    reflectance:
      type: 'rgb'
      value: [0., 0., 0.]
  emitter:
    type: 'area'
    radiance:
      type: 'rgb'
      value: [ 9.040693,  9.697464, 10.583247]

spot: 
  type: 'obj'
  filename: 'outputs/00_assets/spot.obj'
  to_world:
    - type: 'translate'
      value: [-0.561803, -0.323403, 0.079234]
    - type: 'scale'
      value: [0.2, 0.2, 0.2]
    - type: 'rotate'
      axis: [1, 0, 0]
      angle: -90
    - type: 'rotate'
      axis: [0, 1, 0]
      angle: -90
  bsdf:
    type: 'conductor'
    material: 'Au'
    
