# Copyright (c) Meta Platforms, Inc. and affiliates.
# All rights reserved.

# This source code is licensed under the license found in the
# LICENSE file in the root directory of this source tree.

type: 'scene'

PerspectiveCamera:
  type: 'perspective'
  fov: 45
  film:
    type: 'hdrfilm'
    width: 1920
    height: 1080
    rfilter:
      type: 'box'
  
Integrator:
  type: 'path'
  max_depth: 7

main_scene:
  type: 'ply'
  filename: ''
  bsdf:
    type: 'twosided'
    fipt_bsdf:
      type: 'fipt'
      emitter_path: ''
      brdf_path: ''

light_ball:
  type: 'sphere'
  to_world:
    - type: 'translate'
      value: [0.2, 2.25, -1.6]
    - type: 'scale'
      value: [0.15, 0.15, 0.15]
  bsdf:
    type: 'diffuse'
    reflectance:
      type: 'rgb'
      value: [0., 0., 0.]
  emitter:
    type: 'area'
    radiance:
      type: 'rgb'
      value: [25, 25, 25]

sphere_2:
  type: 'sphere'
  to_world:
    - type: 'translate'
      value: [0.125, 1.14, -1.07569]
    - type: 'scale'
      value: [0.25, 0.25, 0.25]
  bsdf:
    type: 'conductor'
    material: 'none'

sphere_3:
  type: 'sphere'
  to_world:
    - type: 'translate'
      value: [0.125, 1.02819, -2]
    - type: 'scale'
      value: [0.15, 0.15, 0.15]
  bsdf:
    type: 'diffuse'
    reflectance: 
      type: 'rgb'
      value: [0.2, 0.25, 0.7]