# Copyright (c) Meta Platforms, Inc. and affiliates.
# All rights reserved.

# This source code is licensed under the license found in the
# LICENSE file in the root directory of this source tree.

type: 'scene'

PerspectiveCamera:
  type: 'perspective'
  fov: 45
  film:
    type: 'hdrfilm'
    width: 1920
    height: 1080
    rfilter:
      type: 'box'
  
Integrator:
  type: 'path'
  max_depth: 7

main_scene:
  type: 'ply'
  filename: ''
  bsdf:
    type: 'twosided'
    fipt_bsdf:
      type: 'fipt'
      emitter_path: ''
      brdf_path: ''

light_ball_0:
  type: 'sphere'
  to_world:
    - type: 'translate'
      value: [-1.72946, 1.95877, -2.19141]
    - type: 'scale'
      value: [0.05, 0.05, 0.05]
  bsdf:
    type: 'diffuse'
    reflectance:
      type: 'rgb'
      value: [0., 0., 0.]
  emitter:
    type: 'area'
    radiance:
      type: 'rgb'
      value: [18, 16, 15]

light_ball_1:
  type: 'sphere'
  to_world:
    - type: 'translate'
      value: [-1.48904, 1.95877, -2.19659]
    - type: 'scale'
      value: [0.05, 0.05, 0.05]
  bsdf:
    type: 'diffuse'
    reflectance:
      type: 'rgb'
      value: [0., 0., 0.]
  emitter:
    type: 'area'
    radiance:
      type: 'rgb'
      value: [15, 15, 12]

light_ball_2:
  type: 'sphere'
  to_world:
    - type: 'translate'
      value: [-1.23297, 1.96617, -2.20512]
    - type: 'scale'
      value: [0.05, 0.05, 0.05]
  bsdf:
    type: 'diffuse'
    reflectance:
      type: 'rgb'
      value: [0., 0., 0.]
  emitter:
    type: 'area'
    radiance:
      type: 'rgb'
      value: [18, 16, 15]

light_ball_3:
  type: 'sphere'
  to_world:
    - type: 'translate'
      value: [-0.982932, 1.96617, -2.21057]
    - type: 'scale'
      value: [0.05, 0.05, 0.05]
  bsdf:
    type: 'diffuse'
    reflectance:
      type: 'rgb'
      value: [0., 0., 0.]
  emitter:
    type: 'area'
    radiance:
      type: 'rgb'
      value: [15, 15, 12]